# Generated by Django 2.0.13 on 2019-03-25 00:18

import aptiv_backend.core.models.aptiv_validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excel',
            old_name='compare_data',
            new_name='compare_json',
        ),
        migrations.AddField(
            model_name='pdf',
            name='num_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aptivvalidate',
            name='output',
            field=models.FileField(default=None, upload_to=aptiv_backend.core.models.aptiv_validate.output_file_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='rev_letter',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
