# Generated by Django 2.0.13 on 2019-03-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190325_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='compare_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
