# Generated by Django 2.0.13 on 2019-03-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190325_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='compare_data',
            new_name='compare_json',
        ),
    ]
