# Generated by Django 2.0.13 on 2019-03-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190325_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
