# Generated by Django 2.0.13 on 2019-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pdf_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
