# Generated by Django 2.0.13 on 2019-03-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_excel_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='compare_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
